"""add avatar_url for users

Revision ID: eb3743963bd4
Revises: b0c849f4d1b6
Create Date: 2023-08-21 18:07:41.705198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb3743963bd4'
down_revision: Union[str, None] = 'b0c849f4d1b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'users', ['avatar_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###
